import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/Provider/Them-provider";

import {
  ClerkProvider,

} from '@clerk/nextjs'
import Nav from "@/components/ui/Nav";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={inter.className}>
          <div className="flex flex-col  px-24">
          <ThemeProvider  attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            
            <Nav/>
            {children}
            </ThemeProvider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
